services:
  api:
    container_name: clone_x
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      MONGODB_URI: mongodb+srv://juanesmontoya92:tdea@electiva2.zd1g5.mongodb.net/
      DB_NAME: clone_x
    volumes:
      - .:/app
    depends_on:
      - mongo_db

  mongo_db:
    container_name: clone_x-mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}